input.onButtonPressed(Button.B, function () {
    Player.change(LedSpriteProperty.Y, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.Y, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.Y, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.Y, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
    basic.pause(100)
    Player.change(LedSpriteProperty.X, 1)
})
let Player: game.LedSprite = null
Player = game.createSprite(4, 0)
basic.forever(function () {
    for (let index = 0; index < 4; index++) {
        for (let index = 0; index < 4; index++) {
            basic.pause(200)
            Player.move(1)
        }
        Player.turn(Direction.Right, 90)
    }
})
